version: '3.8'

services:
  rashan-frontend:
    build:
      context: ./rashanFront
    container_name: rashan-frontend
    working_dir: /app
    volumes:
      - ./rashanFront:/app
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://31.97.111.241:8083/api
      NEXT_PUBLIC_BACKEND_URL_PUBLIC: http://31.97.111.241:8083/storage/public/
    networks:
      - rashan-network

networks:
  rashan-network:
    external: true
