
services:
  rashan-frontend:
    build:
      context: .
    container_name: rashan-frontend
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_BACKEND_URL_PUBLIC: ${NEXT_PUBLIC_BACKEND_URL_PUBLIC}
    networks:
      - rashan-network

networks:
  rashan-network:
    external: false
